<?php


namespace Tests\Feature\Http\Controllers\CartController;


use App\Models\User;
use Tests\Feature\Http\Controllers\BaseControllerTest;

class ShowTest extends BaseControllerTest
{

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanExecuteThisAction()
    {
        $this->withoutExceptionHandling();
        $response = $this->actingAs($this->user)->get(route('cart.show', $this->user->id));
        $response
            ->assertStatus(200)
            ->assertViewIs('home.users.cart')
            ->assertViewHas('user');
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotExecuteThisAction()
    {
        $anotherUser = User::factory()->create();
        $response = $this->actingAs($this->user)->get(route('cart.show', $anotherUser->id));

        $response
            ->assertStatus(403)
            ->assertForbidden();
    }

    /**
     * Test user unauthenticated is redirected to Login.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->get(route('cart.show', $this->user->id));

        $response
            ->assertRedirect(route('login'))
            ->assertStatus(302);
    }
}