<?php

namespace Tests\Feature\Http\Controllers\Roles;

use App\Constants\Roles;
use App\Models\User;
use Database\Seeders\TestDatabaseSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class IndexTest extends TestCase
{

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Test user with permission can see roles list.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanSeeRolesList()
    {
        $admin = User::factory()->create()->assignRole(Roles::SUPER_ADMIN);

        $response = $this->actingAs($admin)->get(route('roles.index'));

        $response
            ->assertStatus(200)
            ->assertViewIs('dashboard.roles.index')
            ->assertViewHas('roles');
    }

    /**
     * Test user without permission can't see roles list.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotSeeRolesList()
    {
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('roles.index'));

        $response->assertStatus(403);
    }

    /**
     * Test user without permission can't see roles list.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->get(route('roles.index'));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('login'));
    }
}
