<?php

namespace Tests\Feature\Http\Controllers\Roles;

use App\Constants\Permissions;
use App\Constants\Roles;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class StoreTest extends TestCase
{

    use RefreshDatabase;

    private $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = User::factory()->create();
    }

    /**
     * Test an user whit permissions can create a role.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanCreateRoles()
    {
        $this->admin->givePermissionTo(Permissions::CREATE_ROLES);

        $response = $this->actingAs($this->admin)->post(route('roles.store'), [
            'name' => $role = 'new role'
        ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('roles.index'))
            ->assertSessionHas('success');

        $this->assertDatabaseHas('roles', [
            'name' => $role
        ]);
    }
}
