<?php


namespace Tests\Feature\Http\Controllers\ProductController;


use App\Constants\Permissions;
use App\Models\Product;
use Tests\Feature\Http\Controllers\BaseControllerTest;

class DeleteTest extends BaseControllerTest
{

    private $product;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = Product::factory()->create();
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanExecuteThisAction()
    {
        $this->admin->givePermissionTo(Permissions::DELETE_PRODUCTS);
        $response = $this->actingAs($this->admin)->delete(route('products.destroy', $this->product->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.index'))
            ->assertSessionHas('success');

        $this->assertDatabaseMissing('products', [
            'id' => $this->product->id
        ]);
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotExecuteThisAction()
    {
        $response = $this->actingAs($this->admin)->delete(route('products.destroy', $this->product->id));

        $response
            ->assertStatus(403)
            ->assertForbidden();
    }

    /**
     * Test user unauthenticated is redirected to Login.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->delete(route('products.destroy', $this->product->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('login'));
    }
}