<?php

namespace Tests\Feature\Http\Controllers\ProductController;

use App\Constants\Permissions;
use App\Models\Product;
use Tests\Feature\Http\Controllers\BaseControllerTest;

class ShowTest extends BaseControllerTest
{

    private $product;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = Product::factory()->create();
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanExecuteThisAction()
    {
        $this->admin->givePermissionTo(Permissions::VIEW_PRODUCTS);

        $response = $this->actingAs($this->admin)->get(route('products.show', $this->product->id));
        $response
            ->assertStatus(200)
            ->assertViewIs('dashboard.products.show')
            ->assertViewHas('product')
            ->assertSee($this->product->name);
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotExecuteThisAction()
    {
        $response = $this->actingAs($this->admin)->get(route('products.show', $this->product->id));

        $response
            ->assertStatus(403)
            ->assertForbidden();
    }

    /**
     * Test user unauthenticated is redirected to Login.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->get(route('products.show', $this->product->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('login'));
    }
}
