<?php

namespace Tests\Feature\Http\Controllers\ProductController;

use App\Constants\Permissions;
use App\Models\Product;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\Feature\Http\Controllers\BaseControllerTest;

class UpdateTest extends BaseControllerTest
{
    use WithFaker;

    private $product;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = Product::factory()->create();
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanExecuteThisAction()
    {
        $this->withoutExceptionHandling();
        $this->admin->givePermissionTo(Permissions::EDIT_PRODUCTS);

        $response = $this->actingAs($this->admin)->put(route('products.update', $this->product->id), [
            'name' => $name = $this->faker->firstName,
            'description' => $description = $this->faker->sentences(3, true),
            'reference' => $reference = $this->faker->numerify('#####'),
            'price' => $price = 20000,
            'stock' => $stock = 5
        ]);

        $response
            ->assertStatus(302)
            ->assertSessionHas('success');

        $this->assertDatabaseHas('products', [
            'name' => $name,
            'description' => $description,
            'reference' => $reference,
            'price' => $price,
            'stock' => $stock
        ]);
    }

    /**
     * Test return errors when data is not valid
     * @return void
     */
    public function testResponseHasErrorsWhenDataIsNotValid()
    {
        $this->admin->givePermissionTo(Permissions::EDIT_PRODUCTS);

        $response = $this->from(route('products.show', $this->product->id))
            ->actingAs($this->admin)->put(route('products.update', $this->product->id), [
                'name' => $name = 0,
                'description' => $description = $this->faker->firstName,
                'reference' => $reference = $this->faker->numerify('###'),
                'price' => $price = 0,
                'stock' => $stock = 0
            ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.show', $this->product->id))
            ->assertSessionHasErrors([
                'name',
                'description',
                'reference',
                'price',
                'stock'
            ]);

        $this->assertDatabaseMissing('products', [
            'name' => $name,
            'description' => $description,
            'reference' => $reference,
            'price' => $price,
            'stock' => $stock
        ]);
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotExecuteThisAction()
    {
        $response = $this->actingAs($this->admin)->put(route('products.update', $this->product->id));

        $response
            ->assertStatus(403)
            ->assertForbidden();
    }

    /**
     * Test user unauthenticated is redirected to Login.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->put(route('products.update', $this->product->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('login'));
    }
}
