<?php


namespace Tests\Feature\Http\Controllers\OrderController;


use App\Models\Cart;
use App\Models\Product;
use App\Models\User;
use Tests\Feature\Http\Controllers\BaseControllerTest;

class StoreTest extends BaseControllerTest
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Product::factory(3)->create()->each(function ($product){
            $this->admin->cart->products()->attach($product->id, [
                'quantity' => 1
            ]);
        });
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithPermissionsCanExecuteThisAction()
    {

        $response = $this->actingAs($this->admin)->post(route('users.orders.store', $this->admin->id));

        $response
            ->assertStatus(302);

        $this->assertDatabaseCount('orders', 1);
    }

    /**
     * Test an user without permissions can't execute this action.
     *
     * @return void
     */
    public function testAnUserWithoutPermissionsCannotExecuteThisAction()
    {
        $anotherUser = User::factory()->create();

        $response = $this->actingAs($this->admin)->post(route('users.orders.store', $anotherUser->id));

        $response
            ->assertStatus(403)
            ->assertForbidden();
    }

    /**
     * Test user unauthenticated is redirected to Login.
     *
     * @return void
     */
    public function testAnUserUnauthenticatedIsRedirectedToLogin()
    {
        $response = $this->get(route('users.orders.store', $this->admin->id));

        $response
            ->assertStatus(302)
            ->assertRedirect(route('login'));
    }
}